// AUTO-GENERATED by scripts/bundle-migrations.ts — do not edit manually.
// Re-generate with: pnpm bundle-migrations
// This file is committed so `bun build --compile` can embed migrations without
// needing filesystem access to packages/db/migrations/ at binary runtime.
import type { MigrationMeta } from 'drizzle-orm/migrator';

export const bundledMigrations: MigrationMeta[] = [
  {
    "sql": [
      "CREATE TABLE `artifacts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`message_id` text NOT NULL,\n\t`conversation_id` text NOT NULL,\n\t`type` text NOT NULL,\n\t`title` text DEFAULT 'Untitled' NOT NULL,\n\t`content` text NOT NULL,\n\t`language` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`message_id`) REFERENCES `messages`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`conversation_id`) REFERENCES `conversations`(`id`) ON UPDATE no action ON DELETE cascade,\n\tCONSTRAINT \"artifact_type_check\" CHECK(\"artifacts\".\"type\" IN ('code', 'diagram', 'doc'))\n);",
      "CREATE INDEX `artifacts_message_id_idx` ON `artifacts` (`message_id`);",
      "CREATE INDEX `artifacts_conversation_id_idx` ON `artifacts` (`conversation_id`);",
      "CREATE TABLE `conversations` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text DEFAULT 'New conversation' NOT NULL,\n\t`provider_id` text,\n\t`model_id` text,\n\t`total_input_tokens` integer DEFAULT 0 NOT NULL,\n\t`total_output_tokens` integer DEFAULT 0 NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text\n);",
      "CREATE INDEX `conversations_updated_at_idx` ON `conversations` (`updated_at`);",
      "CREATE INDEX `conversations_deleted_at_idx` ON `conversations` (`deleted_at`);",
      "CREATE TABLE `messages` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`conversation_id` text NOT NULL,\n\t`role` text NOT NULL,\n\t`content` text,\n\t`tool_calls` text,\n\t`tool_call_id` text,\n\t`input_tokens` integer,\n\t`output_tokens` integer,\n\t`time_to_first_token_ms` integer,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`conversation_id`) REFERENCES `conversations`(`id`) ON UPDATE no action ON DELETE cascade,\n\tCONSTRAINT \"message_role_check\" CHECK(\"messages\".\"role\" IN ('user', 'assistant', 'system', 'tool'))\n);",
      "CREATE INDEX `messages_conversation_id_created_at_idx` ON `messages` (`conversation_id`,`created_at`);",
      "CREATE TABLE `provider_configs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`provider_type` text NOT NULL,\n\t`base_url` text NOT NULL,\n\t`api_key` text,\n\t`default_model` text,\n\t`is_default` integer DEFAULT false NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tCONSTRAINT \"provider_type_check\" CHECK(\"provider_configs\".\"provider_type\" IN ('ollama', 'vllm', 'lmstudio', 'localai', 'llama-cpp', 'custom'))\n);"
    ],
    "bps": true,
    "folderMillis": 1775963647129,
    "hash": "ad0c3f5a9c7d1cfa1cbe9917b4ac12f392acd9a03f0f14f2ce98ce1f93e29f06"
  },
  {
    "sql": [
      "-- Migration 0001: v0.5 additions (branching + system prompt templates)\nALTER TABLE `conversations` ADD COLUMN `branched_from_conversation_id` text REFERENCES `conversations`(`id`) ON DELETE SET NULL;",
      "ALTER TABLE `conversations` ADD COLUMN `branched_from_message_id` text REFERENCES `messages`(`id`) ON DELETE SET NULL;",
      "CREATE INDEX IF NOT EXISTS `conversations_branched_from_idx` ON `conversations` (`branched_from_conversation_id`);",
      "ALTER TABLE `messages` ADD COLUMN `branch_count` integer DEFAULT 0 NOT NULL;",
      "CREATE TABLE IF NOT EXISTS `system_prompt_templates` (\n  `id` text PRIMARY KEY NOT NULL,\n  `name` text NOT NULL,\n  `content` text NOT NULL,\n  `description` text,\n  `is_builtin` integer DEFAULT false NOT NULL,\n  `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n  `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n);",
      "CREATE INDEX IF NOT EXISTS `system_prompt_templates_builtin_name_idx` ON `system_prompt_templates` (`is_builtin`, `name`);"
    ],
    "bps": true,
    "folderMillis": 1775963700000,
    "hash": "f40d90e6c495d04a176340b7a47e722ead06682fc0bddaa8c5cdac1facc10a47"
  },
  {
    "sql": [
      "-- Migration 0002: RAG chunks (embeddings for semantic codebase search)\nCREATE TABLE IF NOT EXISTS `rag_chunks` (\n  `id` text PRIMARY KEY NOT NULL,\n  `file_path` text NOT NULL,\n  `chunk_index` integer NOT NULL,\n  `content` text NOT NULL,\n  `embedding` blob,\n  `indexed_at` text NOT NULL\n);",
      "CREATE INDEX IF NOT EXISTS `rag_chunks_file_path_idx` ON `rag_chunks` (`file_path`);",
      "CREATE INDEX IF NOT EXISTS `rag_chunks_file_chunk_idx` ON `rag_chunks` (`file_path`, `chunk_index`);"
    ],
    "bps": true,
    "folderMillis": 1744502400000,
    "hash": "1f4b3d3829326fc3cbb1bc599a63d6b8ca6c19e122f8e3c547af4d34ca29ed0e"
  },
  {
    "sql": [
      "ALTER TABLE `provider_configs` ADD `auth_mode` text NOT NULL DEFAULT 'none';",
      "ALTER TABLE `provider_configs` ADD `last_tested_at` text;",
      "ALTER TABLE `provider_configs` ADD `last_test_status` text;",
      "ALTER TABLE `provider_configs` ADD `last_test_detail` text;",
      "UPDATE `provider_configs` SET `auth_mode` = 'bearer' WHERE `api_key` IS NOT NULL AND `api_key` != '' AND `api_key` != 'ollama';"
    ],
    "bps": true,
    "folderMillis": 1776000000000,
    "hash": "e29d7025a363840deafb608e31ee8c59d958bceebad8f9c4b366d04121984f61"
  },
  {
    "sql": [
      "ALTER TABLE `conversations` ADD `relay_id` text;",
      "CREATE TABLE `relay_runs` (\n  `id` text PRIMARY KEY NOT NULL,\n  `relay_id` text NOT NULL,\n  `relay_name` text NOT NULL,\n  `conversation_id` text REFERENCES `conversations`(`id`) ON DELETE SET NULL,\n  `input` text NOT NULL,\n  `scout_output` text,\n  `anchor_output` text,\n  `scout_provider_id` text NOT NULL,\n  `scout_model` text NOT NULL,\n  `anchor_provider_id` text NOT NULL,\n  `anchor_model` text NOT NULL,\n  `status` text NOT NULL,\n  `scout_input_tokens` integer,\n  `scout_output_tokens` integer,\n  `anchor_input_tokens` integer,\n  `anchor_output_tokens` integer,\n  `error_message` text,\n  `started_at` text NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),\n  `completed_at` text\n);",
      "CREATE INDEX `relay_runs_relay_id_idx` ON `relay_runs` (`relay_id`);",
      "CREATE INDEX `relay_runs_started_at_idx` ON `relay_runs` (`started_at`);"
    ],
    "bps": true,
    "folderMillis": 1776030000000,
    "hash": "b21268acd1136aabe59f04bad9d229f6b20fd2a417e8319b6c37a50c03892a0a"
  },
  {
    "sql": [
      "-- uplnk v2 flows engine\nALTER TABLE conversations ADD COLUMN source TEXT NOT NULL DEFAULT 'tui';",
      "ALTER TABLE conversations ADD COLUMN imported_from TEXT;",
      "CREATE TABLE flows (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL UNIQUE,\n  version INTEGER NOT NULL DEFAULT 1,\n  source_path TEXT NOT NULL,\n  source_hash TEXT NOT NULL,\n  definition_json TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),\n  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))\n);",
      "CREATE TABLE flow_runs (\n  id TEXT PRIMARY KEY,\n  flow_id TEXT NOT NULL REFERENCES flows(id),\n  flow_version INTEGER NOT NULL,\n  trigger TEXT NOT NULL,\n  status TEXT NOT NULL CHECK(status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')),\n  started_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),\n  ended_at TEXT,\n  input_json TEXT,\n  output_json TEXT,\n  error_json TEXT,\n  parent_run_id TEXT REFERENCES flow_runs(id)\n);",
      "CREATE INDEX flow_runs_flow_id_idx ON flow_runs(flow_id);",
      "CREATE INDEX flow_runs_status_idx ON flow_runs(status);",
      "CREATE TABLE flow_step_results (\n  id TEXT PRIMARY KEY,\n  run_id TEXT NOT NULL REFERENCES flow_runs(id) ON DELETE CASCADE,\n  step_id TEXT NOT NULL,\n  step_index INTEGER NOT NULL,\n  iteration INTEGER NOT NULL DEFAULT 0,\n  status TEXT NOT NULL,\n  started_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),\n  ended_at TEXT,\n  input_json TEXT,\n  output_json TEXT,\n  error_json TEXT,\n  message_id TEXT REFERENCES messages(id),\n  robotic_session_id TEXT\n);",
      "CREATE INDEX flow_step_results_run_idx ON flow_step_results(run_id, step_index, iteration);"
    ],
    "bps": true,
    "folderMillis": 1776031200000,
    "hash": "00c8ef66f3b56e2cd966106afe3a842bd9f859490f2b8b51997782628a038ba3"
  },
  {
    "sql": [
      "-- uplnk v2 robotic mode + altergo integration\nCREATE TABLE robotic_sessions (\n  id TEXT PRIMARY KEY,\n  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),\n  ended_at TEXT,\n  target TEXT NOT NULL,\n  altergo_account TEXT,\n  transport TEXT NOT NULL,\n  goal TEXT NOT NULL,\n  status TEXT NOT NULL CHECK(status IN ('running', 'succeeded', 'failed', 'aborted')),\n  conversation_id TEXT REFERENCES conversations(id),\n  flow_run_id TEXT REFERENCES flow_runs(id)\n);",
      "CREATE INDEX robotic_sessions_status_idx ON robotic_sessions(status);",
      "CREATE TABLE robotic_turns (\n  id TEXT PRIMARY KEY,\n  session_id TEXT NOT NULL REFERENCES robotic_sessions(id) ON DELETE CASCADE,\n  idx INTEGER NOT NULL,\n  direction TEXT NOT NULL,\n  content TEXT NOT NULL,\n  tokens_in INTEGER,\n  tokens_out INTEGER,\n  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),\n  meta_json TEXT\n);",
      "CREATE INDEX robotic_turns_session_idx ON robotic_turns(session_id, idx);",
      "CREATE TABLE altergo_accounts (\n  id TEXT PRIMARY KEY,\n  providers_json TEXT NOT NULL,\n  last_seen_at TEXT NOT NULL,\n  meta_json TEXT\n);",
      "CREATE TABLE altergo_imports (\n  id TEXT PRIMARY KEY,\n  account TEXT NOT NULL,\n  provider TEXT NOT NULL,\n  source_path TEXT NOT NULL UNIQUE,\n  source_hash TEXT NOT NULL,\n  conversation_id TEXT NOT NULL REFERENCES conversations(id),\n  imported_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),\n  message_count INTEGER NOT NULL\n);",
      "CREATE INDEX altergo_imports_account_idx ON altergo_imports(account, provider);"
    ],
    "bps": true,
    "folderMillis": 1776032400000,
    "hash": "096ba382ef6c1b7ce9e9be1bb3dece21a90a9b1dc0cdf10026be093c4e0f551b"
  },
  {
    "sql": [
      "-- uplnk multi-agent core: agent_runs + conversation_agents + ephemeral_agents\n-- plus conversations.mode / conversations.floor_agent_name.\nCREATE TABLE agent_runs (\n  id TEXT PRIMARY KEY,\n  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,\n  root_invocation_id TEXT NOT NULL,\n  parent_invocation_id TEXT,\n  agent_name TEXT NOT NULL,\n  depth INTEGER NOT NULL DEFAULT 0,\n  ancestry_json TEXT NOT NULL DEFAULT '[]',\n  trigger_message_id TEXT REFERENCES messages(id) ON DELETE SET NULL,\n  model TEXT,\n  provider_id TEXT,\n  status TEXT NOT NULL DEFAULT 'running' CHECK(status IN ('running', 'completed', 'errored', 'aborted')),\n  input_tokens INTEGER NOT NULL DEFAULT 0,\n  output_tokens INTEGER NOT NULL DEFAULT 0,\n  error_message TEXT,\n  started_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),\n  ended_at TEXT,\n  CHECK(depth >= 0)\n);",
      "CREATE INDEX agent_runs_conv_started_idx ON agent_runs(conversation_id, started_at);",
      "CREATE INDEX agent_runs_root_idx ON agent_runs(root_invocation_id);",
      "CREATE INDEX agent_runs_parent_idx ON agent_runs(parent_invocation_id);",
      "CREATE TABLE conversation_agents (\n  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,\n  agent_name TEXT NOT NULL,\n  is_ephemeral INTEGER NOT NULL DEFAULT 0,\n  provider_override TEXT,\n  model_override TEXT,\n  joined_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),\n  left_at TEXT,\n  PRIMARY KEY(conversation_id, agent_name, joined_at)\n);",
      "CREATE INDEX conversation_agents_conv_idx ON conversation_agents(conversation_id);",
      "CREATE INDEX conversation_agents_active_idx ON conversation_agents(conversation_id, left_at);",
      "CREATE TABLE ephemeral_agents (\n  id TEXT PRIMARY KEY,\n  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,\n  name TEXT NOT NULL,\n  definition_json TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),\n  UNIQUE(conversation_id, name)\n);",
      "CREATE INDEX ephemeral_agents_conv_name_idx ON ephemeral_agents(conversation_id, name);",
      "ALTER TABLE conversations ADD COLUMN mode TEXT NOT NULL DEFAULT 'single';",
      "ALTER TABLE conversations ADD COLUMN floor_agent_name TEXT;"
    ],
    "bps": true,
    "folderMillis": 1776040000000,
    "hash": "2f55be660b604e97610254375af173320b0e5f3a29d78103739772803b0e9cf5"
  },
  {
    "sql": [
      "-- Attribute messages to specific agents / invocations / turns.\n-- All new columns are nullable (or default-null-safe) so existing rows stay valid.\nALTER TABLE messages ADD COLUMN sender_agent_name TEXT;",
      "ALTER TABLE messages ADD COLUMN addressee_agent_name TEXT;",
      "ALTER TABLE messages ADD COLUMN agent_run_id TEXT REFERENCES agent_runs(id) ON DELETE SET NULL;",
      "ALTER TABLE messages ADD COLUMN turn_id TEXT;",
      "CREATE INDEX messages_conv_sender_idx ON messages(conversation_id, sender_agent_name);",
      "CREATE INDEX messages_agent_run_idx ON messages(agent_run_id);",
      "CREATE INDEX messages_turn_idx ON messages(conversation_id, turn_id);"
    ],
    "bps": true,
    "folderMillis": 1776041200000,
    "hash": "4269f0e060824814ca2e02bc33278ed3ebc2e3d7ab05dcd55b9183adf7033e97"
  }
];
