#!/usr/bin/env bun
/**
 * bundle-migrations.ts
 *
 * Pre-build codegen step. Reads all Drizzle migration SQL files from
 * packages/db/migrations/ and emits packages/db/src/migrations.generated.ts —
 * a TypeScript module that exports the migrations as an inline array.
 *
 * This is required because `bun build --compile` produces a self-contained
 * binary that embeds only JS/TS modules. Drizzle's migrate() normally reads
 * SQL files from disk at runtime, but those files don't exist inside the binary.
 * Embedding the SQL as a static array sidesteps this entirely.
 *
 * Run with:
 *   pnpm bundle-migrations
 *
 * This file is committed to the repo and re-generated whenever a new migration
 * is added (i.e. on every `pnpm build` via the prebuild hook).
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const migrationsDir = join(scriptDir, '../packages/db/migrations');

interface JournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}

interface Journal {
  version: string;
  dialect: string;
  entries: JournalEntry[];
}

const journal: Journal = JSON.parse(
  readFileSync(join(migrationsDir, 'meta/_journal.json'), 'utf8'),
);

const migrations = journal.entries.map((entry) => {
  const sql = readFileSync(join(migrationsDir, `${entry.tag}.sql`), 'utf8');
  return {
    // Trim each statement fragment: the breakpoint marker sits on its own line,
    // so the split produces fragments with leading/trailing whitespace. Filtering
    // out empty strings also guards against a trailing breakpoint.
    sql: sql.split('--> statement-breakpoint').map((s) => s.trim()).filter(Boolean),
    bps: entry.breakpoints,
    folderMillis: entry.when,
    hash: createHash('sha256').update(sql).digest('hex'),
  };
});

const output = [
  '// AUTO-GENERATED by scripts/bundle-migrations.ts — do not edit manually.',
  '// Re-generate with: pnpm bundle-migrations',
  '// This file is committed so `bun build --compile` can embed migrations without',
  '// needing filesystem access to packages/db/migrations/ at binary runtime.',
  "import type { MigrationMeta } from 'drizzle-orm/migrator';",
  '',
  `export const bundledMigrations: MigrationMeta[] = ${JSON.stringify(migrations, null, 2)};`,
  '',
].join('\n');

const outPath = join(scriptDir, '../packages/db/src/migrations.generated.ts');
writeFileSync(outPath, output);
console.log(`Wrote ${migrations.length} migration(s) to packages/db/src/migrations.generated.ts`);
